### ISSUE TITLE
Allow null on user_id

### ISSUE THREAD

**Issue by albertcat** [Team-Tea-Time/laravel-filer#3]
Hi! Great job on the package, is just what I was looking for, a simple way to manage attachments with polymorphic relations. Cool.

Just one note: I think it would be nice that user_id at filer_attachment table could accept the null value. In my case, I'm attaching to a model without any user relation relevance so now I would need to relate the attachement to a dummy user. Allow null in this case will be perfect, I think this would improve the versatility of the package.

Regards!

**Comment by Riari** [comment]
Makes sense. I'll look into this ASAP :)

**Comment by Riari** [comment]
Done: https://github.com/Team-Tea-Time/laravel-filer/releases/tag/1.0.1
