### ISSUE TITLE
Download file using file title

### ISSUE THREAD

**Issue by victorlap** [Team-Tea-Time/laravel-filer#6]
Currently when I am processing a file, php renames the file to a random string like `phpBeceYT`. This is fine, however I would like to download the file with the original name. Therefore I set the title to the original filename. How can this be achieved with laravel-filer? Because right now, when I download the file, I don;t get a file with the correct extension.

**Comment by Riari** [comment]
How the file is stored and named is completely up to you. This package is only designed to be called for files that have already been uploaded/processed - you simply give it some kind of reference to an existing file so it can create a table row for it.

When you download a file via filer's route, you should get it with whatever name and extension it was given.

**Comment by victorlap** [comment]
Yes, exactly. I download the file with the name it is stored on the server. And I want to download it with another name (which I have stored as title). So I guess this is not possible?

**Comment by Riari** [comment]
Ah, I see. In that case, no, it's not supported currently. Open to PRs if you have some idea of how to implement it, otherwise I might have a go at it myself at some point.
